site_name: Acebot

nav:
  - Home: index.md
  - Modules: mods.md
  - Features and commands: features.md
  - Help: helplinks.md
  - FAQ: faq.md
  - Changelog: changes.md

theme: 
  name: material

markdown_extensions:
  - admonition
  - pymdownx.tasklist